export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';  

export const GET_ALL_PRODUCTS = "GET_ALL_PRODUCTS"
export const GET_PRODUCT_BY_ID = "GET_PRODUCT_BY_ID"
export const GET_PRODUCT_BY_CATEGORY = "GET_PRODUCT_BY_CATEGORY"
export const PRODUCT_FETCH_START = "PRODUCT_FETCH_START";
export const PRODUCT_FETCH_FAIL = "PRODUCT_FETCH_FAIL";

export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';